export const fertilizer = [
  {
    _id: "101",
    name: "DAP",
    images: "https://m.media-amazon.com/images/I/51CvpJlQs0L._AC_UL320_.jpg",
    description: "20:20:13",
    price: 1250,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "102",
    name: "DAP",
    images: "https://m.media-amazon.com/images/I/61A6GsX-opL._AC_UL320_.jpg",
    description: "18:46:0",
    price: 1425,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "103",
    name: "POTASH",
    images: "https://kumarfertilizer.netlify.app/images/chemicals/mop.PNG",
    description: "60% k2o",
    price: 1900,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "104",
    name: "UREA",
    images: "https://kumarfertilizer.netlify.app/images/chemicals/urea.png",
    description: "46% N",
    price: 266,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "105",
    name: "CALCIUM",
    images: "https://m.media-amazon.com/images/I/21KmYsSJQjL._AC_UL320_.jpg",
    description: "",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "106",
    name: "COMPLEX",
    images: "https://kumarfertilizer.netlify.app/images/chemicals/calcium2.jpg",
    description: "46% N",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "107",
    name: "SUPER",
    images: "https://kumarfertilizer.netlify.app/images/chemicals/ssp.png",
    description: "16% P2O5",
    price: 650,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "108",
    name: "NPK",
    images: "https://kumarfertilizer.netlify.app/images/chemicals/urea2.png",
    description: "28:28:0",
    price: 1320,
    quantity: 1,
    isStock: true,
  },
];
export const equipment = [
  {
    _id: "1",
    name: "Power Charger",
    images: "https://kumarfertilizer.netlify.app/images/tool/p1.jpg",
    description: "Samson 12V",
    price: 450,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "2",
    name: "Field Switch",
    images: "https://kumarfertilizer.netlify.app/images/tool/p2.jpg",
    description: "20mm Wire",
    price: 50,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "3",
    name: "Nozzle",
    images: "https://kumarfertilizer.netlify.app/images/tool/p3.jpg",
    description: "Flower Type",
    price: 80,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "4",
    name: "Double Motor Pump",
    images: "https://kumarfertilizer.netlify.app/images/tool/p4.jpg",
    description: "B-708 (18L)",
    price: 3166,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "5",
    name: "Spayer Tank",
    images: "https://kumarfertilizer.netlify.app/images/tool/p5.jpg",
    description: "HBO 708 (16L)",
    price: 2599,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "6",
    name: "Gloves",
    images: "https://kumarfertilizer.netlify.app/images/tool/p6.jpg",
    description: "Darit Rubbler",
    price: 110,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "7",
    name: "Battery Sprayer",
    images: "https://kumarfertilizer.netlify.app/images/tool/p7.jpg",
    description: "B- 708 (20L)",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "8",
    name: "Trigger Gun",
    images: "https://kumarfertilizer.netlify.app/images/tool/p8.jpg",
    description: "Hard Plastic",
    price: 70,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "9",
    name: "Water Pump",
    images: "https://kumarfertilizer.netlify.app/images/tool/p9.jpg",
    description: "Single Motor",
    price: 500,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "10",
    name: "Sprayer",
    images: "https://kumarfertilizer.netlify.app/images/tool/p10.jpg",
    description: "4-5 HP",
    price: 6000,
    quantity: 1,
    isStock: true,
  },
];
export const herbicide = [
  {
    _id: "11",
    name: "Saathi",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s11.jpg",
    description: "Herbicide",
    price: 200,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "12",
    name: "Mera71",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s12.jpg",
    description: "Herbicide",
    price: 190,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "13",
    name: "Weedmar-38",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s13.jpg",
    description: "Herbicide",
    price: 285,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "14",
    name: "Weedmar-80",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s16.jpg",
    description: "Herbicide",
    price: 300,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "15",
    name: "Atlantis",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s17.jpg",
    description: "Herbicide",
    price: 250,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "16",
    name: "Roundup",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s18.jpg",
    description: "Herbicide",
    price: 320,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "17",
    name: "Weedmar Super",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s14.jpg",
    description: "Herbicide",
    price: 400,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "18",
    name: "Total",
    images: "https://kumarfertilizer.netlify.app/images/Herbicide/s15.jpg",
    description: "Herbicide",
    price: 80,
    quantity: 1,
    isStock: true,
  },
];

export const pesticide = [
  {
    _id: "1",
    name: "Saaf",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s1.jpg",
    description: "Mancozeb 63%",
    price: 200,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "2",
    name: "Antracol",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s2.jpg",
    description: "Propineb 70%",
    price: 190,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "3",
    name: "Bavistin",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s3.jpg",
    description: "Crystal",
    price: 180,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "4",
    name: "Amistar",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s4.jpg",
    description: "Fungicides",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "5",
    name: "Amistar Top",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s10.jpg",
    description: "Fungicides",
    price: 298,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "6",
    name: "Achook",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s6.jpg",
    description: "Fungicides",
    price: 120,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "7",
    name: "Macobanc",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s7.jpg",
    description: "Fungicides",
    price: 90,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "8",
    name: "Metamack",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s8.jpg",
    description: "Fungicides",
    price: 100,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "9",
    name: "Fossil",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s9.jpg",
    description: "Fungicides",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "10",
    name: "Dhanuka M-45",
    images: "https://kumarfertilizer.netlify.app/images/fungicide/s10.jpg",
    description: "Fungicides",
    price: 560,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "11",
    name: "Monocil",
    images: "https://kumarfertilizer.netlify.app/images/insecticide/s11.jpg",
    description: "Insecticide",
    price: 200,
    quantity: 1,
    isStock: true,
  },
];

export const nutrition = [
  {
    _id: "1",
    name: "Top plush",
    images: "https://kumarfertilizer.netlify.app/images/plant/p1.jpg",
    description: "16% S,N",
    price: 400,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "2",
    name: "Nano Urea",
    images: "https://kumarfertilizer.netlify.app/images/plant/p2.jpg",
    description: "60% N",
    price: 300,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "3",
    name: "Nano Dap",
    images: "https://kumarfertilizer.netlify.app/images/plant/p3.jpg",
    description: "8:16:0",
    price: 1100,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "4",
    name: "Borofat",
    images: "https://kumarfertilizer.netlify.app/images/plant/p4.jpg",
    description: "11% B",
    price: 120,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "5",
    name: "Zinc",
    images: "https://kumarfertilizer.netlify.app/images/plant/p5.jpg",
    description: "33%",
    price: 99,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "7",
    name: "Boron",
    images: "https://kumarfertilizer.netlify.app/images/plant/p7.jpg",
    description: "14.5% B",
    price: 150,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "8",
    name: "Sulphur",
    images: "https://kumarfertilizer.netlify.app/images/plant/p8.jpg",
    description: "20% S",
    price: 70,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "9",
    name: "Sulphate",
    images: "https://kumarfertilizer.netlify.app/images/plant/p9.png",
    description: "22% Sul",
    price: 140,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "10",
    name: "Shimo",
    images: "https://kumarfertilizer.netlify.app/images/plant/p10.jpg",
    description: "Fungicide",
    price: 60,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "12",
    name: "AllWin Wonder",
    images: "https://kumarfertilizer.netlify.app/images/plant/p12.jpg",
    description: "22% C",
    price: 400,
    quantity: 1,
    isStock: true,
  },
];

export const seed = [
  {
    _id: "1",
    name: "BITTER GOURD",
    images: "https://kumarfertilizer.netlify.app/images/seed/s1.jpg",
    description: "VNR NT 77",
    price: 580,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "2",
    name: "TOMATO",
    images: "https://kumarfertilizer.netlify.app/images/seed/s2.jpg",
    description: "VNR 3171",
    price: 180,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "3",
    name: "BRINJAL",
    images: "https://kumarfertilizer.netlify.app/images/seed/s3.jpg",
    description: "F1 Hybrid",
    price: 490,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "4",
    name: "CAULIFLOWER",
    images: "https://kumarfertilizer.netlify.app/images/seed/s4.jpg",
    description: "Clause",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "5",
    name: "BRINJAL",
    images: "https://kumarfertilizer.netlify.app/images/seed/s5.jpg",
    description: "F1 Hybrid",
    price: 298,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "6",
    name: "PEA",
    images: "https://kumarfertilizer.netlify.app/images/seed/s6.jpg",
    description: "F1 Hybrid",
    price: 390,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "7",
    name: "BRINJAL",
    images: "https://kumarfertilizer.netlify.app/images/seed/s7.jpg",
    description: "BSS 1031",
    price: 310,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "8",
    name: "BOTTLE GOURD",
    images: "https://kumarfertilizer.netlify.app/images/seed/s8.jpg",
    description: "F1 Hybrid",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "9",
    name: "BITTER GOURD",
    images: "https://kumarfertilizer.netlify.app/images/seed/s9.jpg",
    description: "SW-811",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "10",
    name: "BITTER GOURD",
    images: "https://kumarfertilizer.netlify.app/images/seed/s10.jpg",
    description: "065 F1 Hybrid",
    price: 850,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "11",
    name: "BITTER GOURD",
    images: "https://kumarfertilizer.netlify.app/images/seed/s11.jpg",
    description: "NT77 Hybrid",
    price: 200,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "12",
    name: "CUCUMBER",
    images: "https://kumarfertilizer.netlify.app/images/seed/s12.jpg",
    description: "F1 Hybrid",
    price: 110,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "13",
    name: "BHINDI",
    images: "https://kumarfertilizer.netlify.app/images/seed/s14.jpg",
    description: "VS-862",
    price: 285,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "14",
    name: "TOMATO",
    images: "https://kumarfertilizer.netlify.app/images/seed/s16.jpg",
    description: "VNR-3171 Hybrid",
    price: 490,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "15",
    name: "BRINJAL",
    images: "https://kumarfertilizer.netlify.app/images/seed/s17.jpg",
    description: "F1 Hybrid",
    price: 250,
    quantity: 1,
    isStock: true,
  },
];
