const fertilizer = [
  {
    _id: "101",
    name: "DAP",
    images: "https://m.media-amazon.com/images/I/51CvpJlQs0L._AC_UL320_.jpg",
    description: "20:20:13",
    price: 1250,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "102",
    name: "DAP",
    images: "https://m.media-amazon.com/images/I/61A6GsX-opL._AC_UL320_.jpg",
    description: "18:46:0",
    price: 1425,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "103",
    name: "POTASH",
    images: "https://kumarfertilizer.netlify.app/images/chemicals/mop.PNG",
    description: "60% k2o",
    price: 1900,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "104",
    name: "UREA",
    images: "/images/chemicals/urea.png",
    description: "46% N",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "105",
    name: "CALCIUM",
    images: "https://m.media-amazon.com/images/I/21KmYsSJQjL._AC_UL320_.jpg",
    description: "",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "106",
    name: "COMPLEX",
    images: "/images/chemicals/calcium2.jpg",
    description: "46% N",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "107",
    name: "SUPER",
    images: "/images/chemicals/ssp.png",
    description: "16% P2O5",
    price: 350,
    quantity: 1,
    isStock: true,
  },
  {
    _id: "108",
    name: "NPK",
    images: "/images/chemicals/urea2.png",
    description: "28:28:0",
    price: 320,
    quantity: 1,
    isStock: true,
  },
];
